---
- hosts: localhost
  tasks:
  - name: "Install required software"
    apt:
      name: "{{ packages }}"
      state: present
    become: true
    vars:
      packages:
      - git
      - docker
      - docker-compose
      - python3-pip
  - name: "Starting Docker"
    become: true
    service:
      name: docker
      state: started
      enabled: yes
  - name: "Launch the docker environment using shell"
    shell: sudo docker run -it --rm -p 8888:8080 tomcat:9.0 